version: "3"
services:
  #  依赖
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi_db
    volumes:
      - ./config/fastapi_db.sql:/docker-entrypoint-initdb.d/fastapi_db.sql
    ports:
      - "3306:3306"
  redis:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"